const variantIdToFile: Record<string, string> = {
  'gold-xray': 'xray-gold',
  'cheat-master-xray': 'xray-cheat-master',
  'gold-onigiri': 'onigiri-gold',
  'cheat-master-onigiri': 'onigiri-cheat-master',
  'gold-overshield': 'overshield-gold',
  'cheat-master-overshield': 'overshield-cheat-master',
  'gold-mega-man': 'mega-man-gold',
  'cheat-master-mega-man': 'mega-man-cheat-master',
  'gold-storm-scout': 'storm-scout-gold',
  'cheat-master-storm-scout': 'storm-scout-cheat-master',
  'gold-bush': 'bush-gold',
  'cheat-master-bush': 'bush-cheat-master',
  'gold-adventure': 'adventure-gold',
  'cheat-master-adventure': 'adventure-cheat-master',
  'gold-8bit': '8-bit-gold',
  'cheat-master-8bit': '8-bit-cheat-master',
  'gold-jonesy': 'jonesy-gold',
  'cheat-master-jonesy': 'jonesy-cheat-master',
  'gold-killswitch': 'killswitch-gold',
  'cheat-master-killswitch': 'killswitch-cheat-master',
  'gold-sonic': 'sonic-gold',
  'cheat-master-sonic': 'sonic-cheat-master',
  'gold-tails': 'tails-gold',
  'cheat-master-tails': 'tails-cheat-master',
  'gold-shadow': 'shadow-gold',
  'cheat-master-shadow': 'shadow-cheat-master',
  'gold-jackrabbit': 'jackrabbit-gold',
  'cheat-master-jackrabbit': 'jackrabbit-cheat-master',
  'gold-crown': 'crown-gold',
  'cheat-master-crown': 'crown-cheat-master',
  'gold-klombo': 'klombo-gold',
  'cheat-master-klombo': 'klombo-cheat-master',
};

export function spriteArtSrc(id: string, variantId?: string): string {
  const mapped = variantIdToFile[id];
  if (mapped) return `/sprites/${mapped}.svg?v=5`;
  if (variantId && variantId !== 'normal' && !id.startsWith(`${variantId}-`)) {
    return `/sprites/${id}-${variantId}.svg?v=5`;
  }
  return `/sprites/${id}.svg?v=5`;
}

const glowById: Record<string, string> = {
  bush: '#4FD07A',
  adventure: '#7EB6E8',
  '8-bit': '#e74c3c',
  jonesy: '#8BB4D9',
  killswitch: '#E24B4B',
  sonic: '#64B5F6',
  tails: '#FFB74D',
  shadow: '#EF5350',
  jackrabbit: '#D7CCC8',
  crown: '#F5C542',
  klombo: '#F0359B',
  's3-batman': '#F4E7C3',
  's3-air': '#81D4FA',
  's3-aura': '#CE93D8',
  's3-earth': '#81C784',
  's3-fire': '#FF8A50',
  's3-water': '#4FC3F7',
  's3-ghost': '#90A4AE',
  's3-llama': '#D7CCC8',
  's3-peeky-peely': '#FFD54F',
  's3-zero-point': '#7C4DFF',
  's3-storm-scout': '#FFD54F',
  's3-fishy': '#4FC3F7',
  's3-demon': '#CE93D8',
  's3-king': '#FFD54F',
  'v4-blaze': '#FF6B35',
  'v4-frostbite': '#00BFFF',
  'v4-thunder': '#FFD700',
  'v4-phantom': '#9370DB',
  'v4-vortex': '#00CED1',
  'v4-echo': '#FF69B4',
  'v4-pulse': '#00FF7F',
  'v4-steelguard': '#708090',
  'v4-wraith': '#483D8B',
  'v4-nova': '#FF4500',
  'v4-zenith': '#E0E0FF',
  'v4-drift': '#FFA500',
  'v4-ember': '#DC143C',
  'v4-shockwave': '#7B68EE',
  'v4-mirage': '#DDA0DD',
  'v4-volt': '#00FFFF',
  'v4-rift': '#9932CC',
  'v4-chronoshift': '#4169E1',
  'v4-entropy': '#2F4F4F',
  'v4-overdrive': '#FF1493',
  'v4-specter': '#B0C4DE',
  'v4-catalyst': '#32CD32',
  'v4-onyx': '#2C2C2C',
  'v4-prism': '#FF6EB4',
  'v4-meridian': '#98FB98',
  xray: '#00e5ff',
  'mega-man': '#2196f3',
  overshield: '#4caf50',
  onigiri: '#f5f5dc',
  'loot-hacker-xray': '#00e5ff',
  'loot-hacker-tails': '#ffb74d',
  'loot-hacker-sonic': '#64b5f6',
  'loot-hacker-shadow': '#ef5350',
  'loot-hacker-8bit': '#5dade2',
  'loot-hacker-bushranger': '#4fd07a',
  'loot-hacker-adventure': '#7eb6e8',
  'loot-hacker-jonesy': '#8bb4d9',
  'loot-hacker-overshield': '#66bb6a',
  'loot-hacker-onigiri': '#f5f5dc',
  'storm-scout': '#FFD54F',
  'loot-hacker-storm-scout': '#ffd54f',
  'loot-hacker-crown': '#F5C542',
  'loot-hacker-klombo': '#22D3EE',
  'loot-hacker-jackrabbit': '#D7CCC8',
  'loot-hacker-killswitch': '#E24B4B',
  'crash-bandicoot': '#FF8A50',
  blinky: '#42A5F5',
  pond: '#4CAF50',
  morgana: '#CE93D8',
  birthday: '#F48FB1',
  'gold-crash-bandicoot': '#FFD54F',
  'gold-blinky': '#FFD54F',
  'gold-pond': '#FFD54F',
  'gold-morgana': '#FFD54F',
  'gold-birthday': '#FFD54F',
  'cheat-master-crash-bandicoot': '#ff5252',
  'cheat-master-blinky': '#ff5252',
  'cheat-master-pond': '#ff5252',
  'cheat-master-morgana': '#ff5252',
  'cheat-master-birthday': '#ff5252',
  'loot-hacker-crash-bandicoot': '#00e5ff',
  'loot-hacker-blinky': '#00e5ff',
  'loot-hacker-pond': '#00e5ff',
  'loot-hacker-morgana': '#00e5ff',
  'loot-hacker-birthday': '#00e5ff',
  'bounty-hunter-xray': '#00e5ff',
  'bounty-hunter-onigiri': '#8D6E63',
  'bounty-hunter-pond': '#4CAF50',
  'bounty-hunter-overshield': '#4CAF50',
  'bounty-hunter-storm-scout': '#FFD54F',
  'bounty-hunter-klombo': '#E040FB',
  'bounty-hunter-shadow': '#EF5350',
  'bounty-hunter-tails': '#FFB74D',
  'bounty-hunter-sonic': '#64B5F6',
  'bounty-hunter-jonesy': '#8BB4D9',
  'bounty-hunter-killswitch': '#E24B4B',
  'bounty-hunter-adventure': '#7EB6E8',
  'bounty-hunter-crash-bandicoot': '#FF8A50',
  'bounty-hunter-bush': '#4FD07A',
  'bounty-hunter-blinky': '#64B5F6',
  'bounty-hunter-jackrabbit': '#D7CCC8',
  'bounty-hunter-crown': '#F5C542',
  'bounty-hunter-8bit': '#9b59b6',
  'bounty-hunter-morgana': '#CE93D8',
  'bounty-hunter-birthday': '#F48FB1',
  'gold-xray': '#FFD54F',
  'cheat-master-xray': '#ff5252',
  'gold-onigiri': '#FFD54F',
  'cheat-master-onigiri': '#ff5252',
  'gold-overshield': '#FFD54F',
  'cheat-master-overshield': '#ff5252',
  'gold-mega-man': '#FFD54F',
  'cheat-master-mega-man': '#ff5252',
  'gold-storm-scout': '#FFD54F',
  'cheat-master-storm-scout': '#ff5252',
  'gold-bush': '#FFD54F',
  'cheat-master-bush': '#ff5252',
  'gold-adventure': '#FFD54F',
  'cheat-master-adventure': '#ff5252',
  'gold-8bit': '#FFD54F',
  'cheat-master-8bit': '#ff5252',
  'gold-jonesy': '#FFD54F',
  'cheat-master-jonesy': '#ff5252',
  'gold-killswitch': '#FFD54F',
  'cheat-master-killswitch': '#ff5252',
  'gold-sonic': '#FFD54F',
  'cheat-master-sonic': '#ff5252',
  'gold-tails': '#FFD54F',
  'cheat-master-tails': '#ff5252',
  'gold-shadow': '#FFD54F',
  'cheat-master-shadow': '#ff5252',
  'gold-jackrabbit': '#FFD54F',
  'cheat-master-jackrabbit': '#ff5252',
  'gold-crown': '#FFD54F',
  'cheat-master-crown': '#ff5252',
  'gold-klombo': '#FFD54F',
  'cheat-master-klombo': '#00E676',
  'phase-dash': '#B388FF',
  'head-shot': '#EF9A9A',
};

export function spriteGlow(id: string): string {
  return glowById[id] ?? '#50e3c2';
}

export function spriteMotionDelay(id: string): string {
  const n = [...id].reduce((sum, ch) => sum + ch.charCodeAt(0), 0);
  return `${(n % 18) * 120}ms`;
}
